services:
  # 1. TU APP (Next.js)
  alcolens:
    container_name: alcolens_app
    build:
      context: .
      dockerfile: ./Dockerfile
    user: root
    restart: always
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      - NODE_ENV=development
      - MONGODB_URI=mongodb+srv://Vercel-Admin-alcolens:JWBjPyArNJRfnglm@alcolens.qcsbyyp.mongodb.net/test?retryWrites=true&w=majority
    volumes:
      - .:/app
    command: pnpm dev
    depends_on:
      - mongo
  # 2. MONGODB
  mongo:
    container_name: alcolens_mongo
    image: mongo:latest
    restart: always
    ports:
      - "27017:27017"
    env_file:
      - .env

# Vol√∫menes Persistentes
volumes:
  mongo_data:
